const router = require('express').Router();
const c = require('../controllers/vehicleController');
const { authenticate, authorize, schoolTenancy } = require('../middleware/auth');
router.use(authenticate); router.use(schoolTenancy);
router.get('/stats/summary', c.getStats);
router.get('/', c.getAll);
router.get('/:id', c.getById);
router.post('/', authorize('super_admin','admin','coordinator'), c.create);
router.put('/:id', authorize('super_admin','admin','coordinator'), c.update);
router.delete('/:id', authorize('super_admin','admin'), c.delete);
module.exports = router;
